label Encoding convert (nominal data into numeric data)

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.DataFrame({"Name":["sadia" , "cow" , "buttderfly" , "cat" , "ball"]})
df.head()

         Name
0       sadia
1         cow
2  buttderfly
3         cat
4        ball

In [3]:
le = LabelEncoder()
df["Name"] = le.fit_transform(df["Name"])

In [6]:
df.head()

   Name
0     4
1     3
2     1
3     2
4     0

In [11]:
data = pd.read_csv("index.csv")
data.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [12]:
la = LabelEncoder()
data["coffee_name"] = la.fit_transform(data["coffee_name"])

In [13]:
data.head(20)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,7
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,6
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,6
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,0
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,7
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,1
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,6
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,1
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,3
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,1
10,2024-03-01,2024-03-01 19:29:17.391,card,ANON-0000-0000-0009,33.8,1
11,2024-03-02,2024-03-02 10:22:06.957,card,ANON-0000-0000-0010,28.9,0
12,2024-03-02,2024-03-02 10:30:35.668,cash,NaN,40.0,7
13,2024-03-02,2024-03-02 10:41:41.249,card,ANON-0000-0000-0011,33.8,1
14,2024-03-02,2024-03-02 11:59:45.484,card,ANON-0000-0000-0012,33.8,1
15,2024-03-02,2024-03-02 14:38:35.535,card,ANON-0000-0000-0013,28.9,0
16,2024-03-02,2024-03-02 16:37:24.475,card,ANON-0000-0000-0014,33.8,1
17,2024-03-02,2024-03-02 17:34:54.969,card,ANON-0000-0000-0004,28.9,0
18,2024-03-03,2024-03-03 10:10:43.981,cash,NaN,40.0,7
19,2024-03-03,2024-03-03 10:27:18.561,card,ANON-0000-0000-0015,38.7,7